title: Newborn IQ
description: Evidence-based newborn care and parenting
theme: minima
baseurl: "/newborniq"
url: "https://siavashsed.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
